#!/bin/sh /etc/rc.common
USE_PROCD=1
CYGNUS_BIN="/usr/bin/cygnus"
CYGNUS_CONF="/etc/cygnus.usr"
LOG_FILE="/var/log/cygnus.log"

start_service() {
    procd_open_instance cygnus
    procd_set_param command /bin/sh -c "
        exec $CYGNUS_BIN auth -f $CYGNUS_CONF >>$LOG_FILE 2>&1
    "
    procd_set_param respawn 10 30 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}